apiVersion: batch/v1
kind: Job
metadata:
  name: apply-certmanager-issuer-job
  annotations:
    helm.sh/hook: post-install
spec:
  template:
    spec:
      containers:
        - name: kubectl
          image: bitnami/kubectl
          command:
            - kubectl
          args:
            - apply
            - -f
            - certmanager-issuer-staging.yaml
            - -f
            - certmanager-issuer-prod.yaml
      restartPolicy: Never
