project: default
source:
  repoURL: 'https://github.com/Cervator/ArtifactoryFuns.git'
  path: ingress-control
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: ingress-control
syncPolicy:
  automated: {}
  syncOptions:
    - CreateNamespace=true
