apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- github.com/argoproj/argo-cd/tree/master/manifests/core-install?ref=v2.7.2
# - argocd-ingress.yaml
# - ingress-controller.yaml
# - artifactory.yaml
