apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
# Note odd protocol setup - otherwise get arbitrary parsing errors
- git::https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.7.2
- app-ingress-control.yaml
- app-artifactory.yaml
- argocd-ingress.yaml
