apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
# Note odd protocol setup - otherwise get arbitrary parsing errors
- git::https://github.com/argoproj/argo-cd/manifests/core-install?ref=v2.7.2

# - argocd-ingress.yaml
# - ingress-controller.yaml
# - artifactory.yaml
