apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secrets
  namespace: jenkins
  labels:
    # Make Argo aware of this resource even if we're deploying it from a local system until secrets are sorted out better
    app.kubernetes.io/part-of: argocd
#    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
#    app.kubernetes.io/instance: {{ .Release.Name | quote }}
#    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
#  annotations:
#    helm.sh/hook: pre-install,pre-upgrade
#    helm.sh/hook-weight: "-5"
#    helm.sh/resource-policy: keep
type: Opaque
data:
  # Take values from GitHub then Base64 encode and paste here - https://github.com/organizations/MovingBlocks/settings/applications/132034
  # Raw to base64: echo -n "abc" | base64
  github-client-id: <encoded output here>
  # Raw to base64: echo -n "def" | base64
  github-client-secret: <encoded output here>
