# We use jenkins at the top level since our chart sub-charts the "jenkins" chart
jenkins:
  # Something goes funny without this even if if installed into the right namespace
  # Specifically some agent namespace settings and URLs end up reverting to "default"
  namespaceOverride: jenkins

  persistence:
    storageClass: ssd
    size: 200Gi

  # Stuff for the main server - see other values files for more specific stuff
  controller:
    resources:
      requests:
        cpu: "250m"
        memory: "2Gi"
      limits:
        cpu: "2000m"
        memory: "6Gi"
    jenkinsAdminEmail: terasology@gmail.com
    numExecutors: 1
    executorMode: EXCLUSIVE
    customJenkinsLabels: "main"

    # Pull secrets from Kubernetes and set them as env vars on the pod for JCasC to use later
    containerEnv:
      - name: GITHUB_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: jenkins-secrets
            key: github-client-id
      - name: GITHUB_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: jenkins-secrets
            key: github-client-secret

    ingress:
      enabled: true
      #hostName: jenkins.terasology.io
      hostName: jenkins.aetas-aetherius.com
      #resourceRootUrl: content.terasology.io
      resourceRootUrl: content.aetas-aetherius.com
      tls:
      - hosts:
        - jenkins.aetas-aetherius.com
        - content.aetas-aetherius.com 
        #- jenkins.terasology.io
        #- content.terasology.io
        secretName: jenkins-tls-secret
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: nginx
